apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCVTB2GfdOK/kttCFZD9QnG6F5gP4FWR3CgrKU8DS7doKp2uccG9eOhPUMD9/besncxco7b28tzWcUkx5zJ3g6UwInTf5giBgNL4FIR1nBsI3hGn5D2kbxot8vV2IkscrEr6BAaPhUubslSohHhTHuK3BAL+NyPJTh+NDY36DGzm1j2z6Ump+7tDlfvomuF/kAsvwoJ7O+RCyBARMkD9obMOKBp4md8M46Jkj0W9rk+3IWdYqFZ52TVC3XSshesx7aDPa1Xfdnr68x7OQrOG7TnacD4ueKDK5Zs8p3cGsfqaVPh9LFdC7TqEtXMO+fkxd+iY+VpRj9E6Dnn/CHbz5dc2yL1Qr1nceBOIJe0096v45S1ZuYPjmzBuwDN91A6oJnBbz1EuKqy595rl3LiR65ppDzqSD4I3PakWBJ959MgZcWlkfUAOCLEUMRLqdABH+9wH9u12nK4qV80q6R2OlsYiecVCcE8mjZhLMG3Fcln2abmqLrNpLYdDnKoP4/Jmewxa8G+LvME6Sx6y+mfv1TIVKS7D1ox0jGOQpPOmW6yInqEPefyyVErh0OIW+JyW2KiUfpHLcIeVLnoJhoHNJ54hkQR8tomyb606UxijcSlag5wQ1n9O1kPvEkiN3kDZdr3oPbmQHw+zN1MHUkgaKSVDygEE+/5Ict6PfM144clCQhKlW+8AyQGLZc7NjVW+A6FDnxioEbM5X/Cr5jMvLkQKvpJ9A==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
