apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAfX0F3qeq88VnMGQR6gGa6PFZy42k87qyl+8F3IoFJGRdnjicWcDnWRVS6EkIx2z69MT343C9WGsnZacdWtMq67koywQw2VaxY789UNXhAjL9j6X1SYfQ2cY5n5MrR+8mzrSTmUMgNk5KYeTCXM+bYM1gSceVUTILgiWqDl4eOlDNzdGNmdU4Uv2vz6gDfLCn2L9d3uD1seYiwuVpuylkm4i/SesDbPm96sJmrwmXd0lSQgY6DLL+nXBDrzYg8mg+Sx4Gt0tQ84mQEiDM3kGKvr60ddUYlMEefSUF0UiwB4dFrJDSPGLKoDqYFdbb5IyrEaLd3iqMhYVsq08nWzQvWgyWwzleXWUz8vf68OAin8MZNqtRJWCpjWurC8nwRgaf6qKvFsNzvDHapt/amEZY+so1iQ2QFosUR4BcR6JeMHWPpS4//GwxElCsSlKw4NFOulIy/qoYGt4luYit9jgBdmoxuEYquBDiW7SlPXHnTIG+rqgpPGIqPpgTCXlrVY6XVw4+LMInweB93dDpavXqKUNtbBseF90vAdythjELtBbkwonrjJTaOp81HRER5F90GMLhnwafiW3qFv+h9QFHWVHAV2IgzfpX0fUwgkev0XiC764hTN5AhFoUO/7Ye0rTU21iZuR8A2ao0n2GM9AFCRQ3tjNzfvIm0oaCpPW+QllOjLS7J6aPCHAIQpV98l612HWzgSTVcuKlLyf4OGCR71yG3WA==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
