apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBONTgdibetimUYRfp7Es/cBhTHTJpvVmik4uqUF0QRyutmHz0Es268ph/XaDjpDSs8w48nT5NEQdb6SGUBIOvMjKVcNHm3xlvGJzSWB4zj4Fvwd/MfIcADPZWC6BWq4oaSmQvJKzv6brR9tM9Lq/3g3Rfr4bK/7sy8rjMFMYRqslm1x89vZ79DeijNxKJm/VLdiTo9xd7J3ARcKwmIbPJql9wwyGMEbbXjT7mk90OUFoabEPRoDkdEc/Qw/j5pvq76qbneZSU9nf65FRDvSPlOYYbymTRzqERoNAZg/demGBwaFQZ5ijmAc0A31TARfVBC2d4sRtzNctIvyIV9fxwoYhbDkkmAI36hsOMSHZvRvF2fumXicJwwvsLCSAOL2hNkS8BjEg0PD5op5VzT27sLrxLk4oZuafVi1wyc0b92SW3T8WYO7QjU3GQm+25PWLo9av3fk8C3xqkwEvCAit+70D9QpgtkWXxK7d2W7oiF0ulVrGYJEfm/DgybiLBQ4zQseMrvhFQ/OWMMR4G+PK9+VknSWrfWaISOejCOq5Q++QIfwVWYl4873qSfzYZtFFkISPZUFDxi/6h/Qt4xWvrubCVxFsvkL9/lV2wl8yWoMKSp4jPcUEOFuSJCjAd6sFvkDXed9C0K2x1mlZW4sRsXu4tBbqEC6rQtjx650aCq1zliwAq6zoN5RWZMFsPN3g+C5Z7WpOCLxGti1TqG2FjkdylrfQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
