apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBmnxWOx0h5hu/lRVnsyuSCz9s+Ym/wp18GtKCh8HKBHnceyRdlGqei41NP3DGPr3fhpjre/ssT+eoOnQMTEarPiK+8LGvsxt1nB8bw+UAvsSwXahaLQ6SxUadNFKncOon+O5+5+u+Q9i+yYT4KjJH/BrTi2Gxkm8/abDAqnu1ieh2U4PlTr8p6EaF4XiVhvYiTQf0YmJ830JUz/cYDYXhHRUPYBLDP10ygemt01KntXWE+KH/02oaQIkl1aTYUsdLBTfout5kdOs32PoJu2mbwzsSItThiJTBxPdStjOJKMnsAc8ukh6r33d8GeG9V84Eoovk7VYHJujWo4xqvzYDOGL16hd6ay/QufqlWpHMobvkkS0Ml9tNDLswia3xVECzvBWvn8WZ+UVTCsYSHgqxlW9L+RULS+NKPHPROyOl6CLqTxM5KMe9+MLOBOaP7ZDdn/21osBJ+2IABVL2sfzG519tJUpH7+i3u++HZVHH/XuyDzigcFo5hHkE2vEPfiMHGiimTltyjNj8RLv+B28UpNYERRA2t6xvWh3d9YjOskEzzr0P8VlO7u9+jWIKoV7R5cDt8Ft0d6shSY2wQiLEDKmrzqNQxQn2Ft/YmL6UnW52Q+WjNN/vbW4raqWoymtEOaJNu3zFFNRzglVAddJkqRBLmWPj1rJhTcTPJoCL0JTSx5VSe3S+72U6/AkhlSrKASl6UuGS/tiSfkISIKb3uY8DTkQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
